// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[id].tsx";
import * as $1 from "./routes/_404.tsx";
import * as $2 from "./routes/api/register.ts";
import * as $3 from "./routes/api/winners.ts";
import * as $4 from "./routes/index.tsx";
import * as $5 from "./routes/leaderboard.tsx";
import * as $$0 from "./islands/identifier.tsx";
import * as $$1 from "./islands/text.tsx";

const manifest = {
  routes: {
    "./routes/[id].tsx": $0,
    "./routes/_404.tsx": $1,
    "./routes/api/register.ts": $2,
    "./routes/api/winners.ts": $3,
    "./routes/index.tsx": $4,
    "./routes/leaderboard.tsx": $5,
  },
  islands: {
    "./islands/identifier.tsx": $$0,
    "./islands/text.tsx": $$1,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
